# Generated by Django 5.0.14 on 2026-07-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_health", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repohealthscore",
            name="green_flags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of positive strings for the user (e.g., 'Active maintainership').",
            ),
        ),
        migrations.AlterField(
            model_name="repohealthscore",
            name="red_flags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of warning strings for the user (e.g., 'Project appears abandoned').",
            ),
        ),
        migrations.AlterField(
            model_name="repohealthscore",
            name="sentiment_score",
            field=models.FloatField(
                blank=True,
                help_text="Aggregated TextBlob polarity score of recent PR comments (-1.0 to 1.0).",
                null=True,
            ),
        ),
    ]
