# Generated by Django 5.0.14 on 2026-07-21 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_health", "0002_alter_repohealthscore_green_flags_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintainerWorkloadProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "active_prs_assigned",
                    models.IntegerField(
                        default=0,
                        help_text="Number of active PRs assigned to the maintainer.",
                    ),
                ),
                (
                    "avg_time_to_review_hours",
                    models.FloatField(
                        default=0.0,
                        help_text="Average time taken to review PRs in hours.",
                    ),
                ),
                (
                    "recent_issue_volume",
                    models.IntegerField(
                        default=0,
                        help_text="Volume of issues assigned in the last 7 days.",
                    ),
                ),
                (
                    "burnout_risk_score",
                    models.CharField(
                        choices=[
                            ("Low", "Low"),
                            ("Medium", "Medium"),
                            ("High", "High"),
                        ],
                        default="Low",
                        max_length=20,
                    ),
                ),
                ("last_analyzed_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workload_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
