# Generated by Django 5.0.14 on 2026-07-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plugin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("display_name", models.CharField(max_length=200)),
                ("version", models.CharField(max_length=50)),
                ("api_version", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                ("author", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=False)),
                ("manifest", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
