from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Message(models.Model):
    room_id = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="messages")
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    parent = models.ForeignKey(
        "self",
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        related_name="replies",
        help_text="The parent message if this is a reply in a thread.",
    )

    objects = models.Manager()  # type: ignore

    class Meta:
        ordering = ["created_at"]

    def __str__(self):
        return f"[{self.room_id}] {self.user.username}: {self.content[:20]}"


class UserPublicKey(models.Model):
    """
    Stores a user's X25519 public key (base64-encoded) for E2E DM encryption.
    The corresponding private key NEVER leaves the client.
    """

    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name="public_key",
    )
    # Base64-encoded X25519 public key generated by libsodium on the client
    public_key = models.TextField(
        help_text="Base64-encoded X25519 public key (32 bytes). Generated client-side."
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.user.username} public key"


class DirectMessage(models.Model):
    """
    A direct message between two users.
    The message content is encrypted client-side using libsodium box encryption
    (X25519 key exchange + XSalsa20-Poly1305). The server stores only ciphertext.
    """

    sender = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="sent_direct_messages",
    )
    recipient = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="received_direct_messages",
    )
    # Base64-encoded ciphertext produced by libsodium box.seal / box
    encrypted_content = models.TextField(
        help_text="Base64-encoded ciphertext. Encrypted client-side; server cannot read this."
    )
    # Base64-encoded nonce (24 bytes) used during encryption
    nonce = models.CharField(
        max_length=64,
        help_text="Base64-encoded nonce used for this message's encryption.",
    )
    # Tracks whether recipient has read the message (for UX only — no security implication)
    is_read = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    objects = models.Manager()  # type: ignore

    class Meta:
        ordering = ["created_at"]

    def __str__(self):
        return f"DM from {self.sender.username} to {self.recipient.username} at {self.created_at}"
