# Generated by Django 5.1.15 on 2026-06-30 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_pushsubscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notif_type",
            field=models.CharField(
                choices=[
                    ("badge", "Badge Earned"),
                    ("comment", "New Comment"),
                    ("achievement", "Achievement Unlocked"),
                ],
                max_length=20,
            ),
        ),
    ]
