# Generated by Django 5.0.14 on 2026-07-15 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_alter_notification_notif_type"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="notification",
            new_name="idx_recipientis_read",
            old_name="notificatio_recipie_4e3567_idx",
        ),
    ]
