# Generated by Django 5.0.14 on 2026-07-16 13:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ErrorGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("message", models.TextField()),
                ("module", models.CharField(db_index=True, max_length=255)),
                ("count", models.PositiveIntegerField(default=0)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("acknowledged", "Acknowledged"),
                            ("resolved", "Resolved"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("cooldown_days", models.PositiveIntegerField(default=7)),
            ],
        ),
        migrations.CreateModel(
            name="ErrorEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raw_message", models.TextField()),
                ("stacktrace", models.TextField(blank=True)),
                ("request_id", models.CharField(blank=True, max_length=100, null=True)),
                ("user_id", models.CharField(blank=True, max_length=100, null=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="errors.errorgroup",
                    ),
                ),
            ],
        ),
    ]
