# Generated by Django 5.1.15 on 2026-06-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="bonus_points",
            field=models.PositiveIntegerField(
                default=0, help_text="Bonus points awarded during a multiplier event."
            ),
        ),
    ]
