# Generated by Django 5.1.15 on 2026-06-24 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_issue_bonus_points"),
        ("dashboard", "0002_streakfreeze"),
    ]

    operations = []
