# Generated by Django 5.0.14 on 2026-07-09 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_merge_0002_issue_bonus_points_0002_streakfreeze'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who soft-deleted this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issue',
            name='deletion_reason',
            field=models.TextField(blank=True, help_text='Reason for deletion'),
        ),
    ]
