# Generated by Django 5.0.14 on 2026-07-13 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_issue_deleted_at_issue_deleted_by_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StreakFreeze',
        ),
    ]
