# Generated by Django 4.2.30 on 2026-06-20 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SandboxExecutionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "command",
                    models.TextField(
                        help_text="The command the user attempted to execute."
                    ),
                ),
                (
                    "accepted",
                    models.BooleanField(help_text="Whether the command was accepted."),
                ),
                (
                    "feedback",
                    models.TextField(
                        blank=True, help_text="Feedback returned to the user."
                    ),
                ),
                (
                    "score_delta",
                    models.IntegerField(
                        help_text="Score change resulting from this attempt."
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the attempt was made."
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who attempted the command.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sandbox_execution_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
