# Generated by Django 5.1.15 on 2026-06-30 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sandbox", "0002_collabsession_collabsessionlog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExecutionViolationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_identifier",
                    models.CharField(
                        help_text="Fallback for anonymous users (e.g., channel name)",
                        max_length=255,
                    ),
                ),
                ("code_snippet", models.TextField()),
                (
                    "violation_type",
                    models.CharField(
                        choices=[
                            ("memory", "Memory Limit Exceeded"),
                            ("timeout", "Execution Timeout"),
                            ("security", "AST Security Violation"),
                            ("concurrency", "Concurrency Limit Exceeded"),
                        ],
                        max_length=20,
                    ),
                ),
                ("details", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="execution_violations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
