# Generated by Django 5.1.15 on 2026-07-03 03:31

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sandbox", "0004_codesnapshot"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the project.", max_length=255
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who owns this project.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sandbox_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        help_text="The full file path within the project (e.g., src/index.js).",
                        max_length=1024,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, help_text="The code content of the file."
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="javascript",
                        help_text="The language of the file.",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        help_text="The project this file belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="sandbox.project",
                    ),
                ),
            ],
            options={
                "ordering": ["path"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "path"), name="unique_project_file_path"
                    )
                ],
            },
        ),
    ]
