# Generated by Django 5.1.15 on 2026-07-03 17:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sandbox", "0008_snippetcollection_codesnippet"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspaceSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the snapshot", max_length=255),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description of the snapshot"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Store editor layout, execution settings, etc.",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this snapshot can be forked by anyone",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="sandbox.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SnapshotFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("path", models.CharField(max_length=1024)),
                ("content", models.TextField(blank=True)),
                ("language", models.CharField(default="javascript", max_length=50)),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="sandbox.workspacesnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["path"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("snapshot", "path"), name="unique_snapshot_file_path"
                    )
                ],
            },
        ),
    ]
