# Generated by Django 5.1.15 on 2026-07-03 16:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sandbox", "0008_snippetcollection_codesnippet"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TemplateCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProjectTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("language", models.CharField(default="javascript", max_length=50)),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this template is visible to all users",
                    ),
                ),
                (
                    "is_official",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is an official system template",
                    ),
                ),
                ("use_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="templates",
                        to="sandbox.templatecategory",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_official", "-use_count", "name"],
            },
        ),
        migrations.CreateModel(
            name="TemplateFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("path", models.CharField(max_length=1024)),
                ("content", models.TextField(blank=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="sandbox.projecttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["path"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("template", "path"), name="unique_template_file_path"
                    )
                ],
            },
        ),
    ]
