# Generated by Django 5.1.15 on 2026-07-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sandbox", "0010_terminalsession_terminalcommand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="terminalcommand",
            name="command",
            field=models.TextField(blank=True),
        ),
    ]
