# Generated by Django 4.2.30 on 2026-07-06 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sandbox", "0012_merge_20260706_1159"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="terminalsession",
            options={},
        ),
        migrations.DeleteModel(
            name="ProjectTemplate",
        ),
        migrations.DeleteModel(
            name="SnapshotFile",
        ),
        migrations.DeleteModel(
            name="TemplateCategory",
        ),
        migrations.DeleteModel(
            name="TemplateFile",
        ),
        migrations.DeleteModel(
            name="TerminalCommand",
        ),
        migrations.DeleteModel(
            name="WorkspaceLayout",
        ),
        migrations.DeleteModel(
            name="WorkspaceSnapshot",
        ),
    ]
