# Generated by Django 5.0.14 on 2026-07-13 02:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0013_remove_snapshotfile_snapshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the snapshot', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description of the snapshot')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Store editor layout, execution settings, etc.')),
                ('is_public', models.BooleanField(default=False, help_text='Whether this snapshot can be forked by anyone')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(help_text='The project this snapshot was taken from.', on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='sandbox.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SnapshotFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.CharField(help_text='The full file path within the snapshot (e.g., src/index.js).', max_length=1024)),
                ('content', models.TextField(blank=True, help_text='The code content of the file.')),
                ('language', models.CharField(default='javascript', help_text='The language of the file.', max_length=50)),
                ('snapshot', models.ForeignKey(help_text='The snapshot this file belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='sandbox.workspacesnapshot')),
            ],
            options={
                'ordering': ['path'],
            },
        ),
        migrations.AddConstraint(
            model_name='snapshotfile',
            constraint=models.UniqueConstraint(fields=('snapshot', 'path'), name='unique_snapshot_file_path'),
        ),
    ]
