# Generated by Django 5.0.14 on 2026-07-15 13:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sandbox", "0015_maintainerscenario_maintainerevaluation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConflictScenario",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "description",
                    models.TextField(help_text="What the user needs to accomplish."),
                ),
                ("language", models.CharField(default="python", max_length=50)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                (
                    "base_code",
                    models.TextField(help_text="The common ancestor (base) code."),
                ),
                (
                    "current_code",
                    models.TextField(
                        help_text="The current branch version (HEAD) of the file."
                    ),
                ),
                (
                    "incoming_code",
                    models.TextField(
                        help_text="The incoming branch version of the file."
                    ),
                ),
                (
                    "expected_resolution",
                    models.TextField(
                        help_text="The correct/expected resolved file content."
                    ),
                ),
                (
                    "hint",
                    models.TextField(
                        blank=True, help_text="Optional hint shown to struggling users."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["difficulty", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConflictAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "submitted_code",
                    models.TextField(
                        help_text="The user's final submitted merged file."
                    ),
                ),
                (
                    "passed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the submitted code matched the expected resolution.",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Reason for failure (e.g., unresolved markers).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conflict_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="sandbox.conflictscenario",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
