# Generated by Django 5.0.14 on 2026-07-15 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sandbox", "0015_collabsession_allowed_users_collabsession_project"),
        ("sandbox", "0015_maintainerscenario_maintainerevaluation"),
    ]

    operations = []
