# Generated by Django 5.0.14 on 2026-07-16 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sandbox", "0016_conflictscenario_conflictattempt"),
        ("sandbox", "0016_merge_20260715_1924"),
        ("sandbox", "0016_merge_20260715_1959"),
        ("sandbox", "0016_merge_20260715_2013"),
        ("sandbox", "0016_pipelineexecution_pipelinejob"),
    ]

    operations = []
