# Generated by Django 5.0.14 on 2026-07-16 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sandbox", "0017_merge_20260715_2159"),
        ("sandbox", "0017_merge_20260716_1300"),
        ("sandbox", "0017_merge_20260716_1330"),
    ]

    operations = []
