# Generated by Django 5.0.14 on 2026-07-16 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sandbox", "0018_merge_20260716_2338"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LicenseScenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the scenario.", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Context of the PR and base project."),
                ),
                (
                    "base_project_license",
                    models.CharField(
                        help_text="License of the base project (e.g., 'MIT').",
                        max_length=100,
                    ),
                ),
                (
                    "difficulty",
                    models.IntegerField(default=1, help_text="Difficulty level (1-5)."),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="conflictattempt",
            options={},
        ),
        migrations.AlterModelOptions(
            name="pipelineexecution",
            options={},
        ),
        migrations.CreateModel(
            name="LicenseAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approved",
                    models.BooleanField(
                        help_text="Did the user approve or reject the PR?"
                    ),
                ),
                (
                    "is_successful",
                    models.BooleanField(
                        default=False, help_text="Was the user's decision correct?"
                    ),
                ),
                (
                    "feedback",
                    models.TextField(
                        blank=True,
                        help_text="Feedback provided to the user after the attempt.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="license_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sandbox.licensescenario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DependencyDiff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "package_name",
                    models.CharField(
                        help_text="Name of the package or file.", max_length=255
                    ),
                ),
                (
                    "package_license",
                    models.CharField(
                        help_text="License of the package (e.g., 'GPLv3', 'Commercial').",
                        max_length=100,
                    ),
                ),
                (
                    "diff_text",
                    models.TextField(
                        help_text="Mock code diff showing the dependency being added."
                    ),
                ),
                (
                    "is_violation",
                    models.BooleanField(
                        default=False,
                        help_text="Does this dependency violate the base project license?",
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True,
                        help_text="Explanation of why this is or isn't a violation.",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependencies",
                        to="sandbox.licensescenario",
                    ),
                ),
            ],
        ),
    ]
