# Generated by Django 5.0.14 on 2026-07-16 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sandbox", "0018_merge_20260716_2335"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DialogueNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "node_id",
                    models.CharField(
                        help_text="Unique ID within the scenario (e.g., 'start', 'end_success').",
                        max_length=100,
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="The text spoken by the simulated user or system."
                    ),
                ),
                (
                    "is_endpoint",
                    models.BooleanField(
                        default=False, help_text="Does this node end the scenario?"
                    ),
                ),
                (
                    "is_successful",
                    models.BooleanField(
                        default=False,
                        help_text="If endpoint, was it successfully resolved?",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModerationScenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the scenario.", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Context of the situation."),
                ),
                (
                    "initial_tension",
                    models.IntegerField(
                        default=50, help_text="Starting tension level (0-100)."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="conflictattempt",
            options={},
        ),
        migrations.AlterModelOptions(
            name="pipelineexecution",
            options={},
        ),
        migrations.CreateModel(
            name="DialogueChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "to_node_id",
                    models.CharField(
                        help_text="The node_id this choice leads to.", max_length=100
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="The response or action text for the player."
                    ),
                ),
                (
                    "tension_delta",
                    models.IntegerField(
                        default=0,
                        help_text="Change in tension (+ increases tension, - decreases).",
                    ),
                ),
                (
                    "is_moderation_action",
                    models.BooleanField(
                        default=False,
                        help_text="Is this a moderation action (e.g. Ban User)?",
                    ),
                ),
                (
                    "from_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="sandbox.dialoguenode",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModerationAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_tension", models.IntegerField(default=50)),
                ("is_completed", models.BooleanField(default=False)),
                ("is_successful", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "current_node",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sandbox.dialoguenode",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderation_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sandbox.moderationscenario",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="dialoguenode",
            name="scenario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nodes",
                to="sandbox.moderationscenario",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dialoguenode",
            unique_together={("scenario", "node_id")},
        ),
    ]
