# Generated by Django 5.0.14 on 2026-07-18 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sandbox", "0017_merge_20260716_1436"),
        ("sandbox", "0017_triageissue_triageattempt"),
        ("sandbox", "0018_merge_20260716_1841"),
        ("sandbox", "0018_merge_20260716_1849"),
        ("sandbox", "0019_dialoguenode_moderationscenario_and_more"),
        ("sandbox", "0019_licensescenario_alter_conflictattempt_options_and_more"),
    ]

    operations = []
