# Generated by Django 5.0.14 on 2026-07-21 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sandbox", "0020_merge_20260718_1400"),
    ]

    operations = [
        migrations.AlterField(
            model_name="triageattempt",
            name="label_score",
            field=models.IntegerField(
                default=0, help_text="Score for label accuracy (0–50)."
            ),
        ),
        migrations.AlterField(
            model_name="triageattempt",
            name="response_score",
            field=models.IntegerField(
                default=0, help_text="Score for response quality (0–50)."
            ),
        ),
        migrations.AlterField(
            model_name="triageattempt",
            name="total_score",
            field=models.IntegerField(default=0, help_text="Combined score (0–100)."),
        ),
        migrations.AlterField(
            model_name="triageissue",
            name="raw_issue_body",
            field=models.TextField(
                help_text="The poorly written body of the simulated issue."
            ),
        ),
    ]
