# Generated by Django 5.0.14 on 2026-07-20 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sandbox", "0020_merge_20260718_1400"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ADRScenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the ADR scenario.", max_length=255
                    ),
                ),
                (
                    "context",
                    models.TextField(
                        help_text="Context of the architectural decision."
                    ),
                ),
                (
                    "constraints",
                    models.TextField(
                        help_text="System constraints (e.g., high read throughput)."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="triageattempt",
            name="label_score",
            field=models.IntegerField(
                default=0, help_text="Score for label accuracy (0–50)."
            ),
        ),
        migrations.AlterField(
            model_name="triageattempt",
            name="response_score",
            field=models.IntegerField(
                default=0, help_text="Score for response quality (0–50)."
            ),
        ),
        migrations.AlterField(
            model_name="triageattempt",
            name="total_score",
            field=models.IntegerField(default=0, help_text="Combined score (0–100)."),
        ),
        migrations.AlterField(
            model_name="triageissue",
            name="raw_issue_body",
            field=models.TextField(
                help_text="The poorly written body of the simulated issue."
            ),
        ),
        migrations.CreateModel(
            name="ADROption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the architectural option.", max_length=255
                    ),
                ),
                ("pros", models.TextField(help_text="Pros of this option.")),
                ("cons", models.TextField(help_text="Cons of this option.")),
                (
                    "is_optimal",
                    models.BooleanField(
                        default=False, help_text="Is this the optimal choice?"
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="sandbox.adrscenario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ADRAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_successful",
                    models.BooleanField(
                        default=False, help_text="Did the user pick the optimal option?"
                    ),
                ),
                (
                    "feedback",
                    models.TextField(
                        blank=True, help_text="Feedback based on the user's choice."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adr_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "selected_option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sandbox.adroption",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sandbox.adrscenario",
                    ),
                ),
            ],
        ),
    ]
