# Generated by Django 5.0.14 on 2026-07-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='content_type',
            field=models.CharField(choices=[('lesson', 'Lesson'), ('challenge', 'Challenge'), ('quiz', 'Quiz'), ('oss_issue', 'OSS Issue')], max_length=20),
        ),
        migrations.CreateModel(
            name='OSSIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_name', models.CharField(max_length=255)),
                ('issue_number', models.IntegerField()),
                ('title', models.CharField(max_length=512)),
                ('url', models.URLField(max_length=1024)),
                ('labels', models.JSONField(default=list)),
                ('difficulty', models.CharField(blank=True, max_length=50, null=True)),
                ('is_open', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('repo_name', 'issue_number')},
            },
        ),
    ]
