# Generated by Django 4.2.30 on 2026-06-22 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0003_alter_helprequest_status_bookmark"),
        ("progress", "0003_exerciseattempt_organization_and_more"),
    ]

    operations = []
