# Generated by Django 4.2.30 on 2026-06-22 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0004_merge_20260622_0937"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Bookmark",
        ),
    ]
