# Generated by Django 6.0.6 on 2026-06-08 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0004_add_lessonprogress_indexes'),
        ('progress', '0004_alter_helprequest_status_quizattempt'),
    ]

    operations = [
    ]
