# Generated by Django 5.1.15 on 2026-06-12
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0006_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonprogress',
            name='attempt_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
