# Generated by Django 5.1.15 on 2026-06-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0006_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
