# Generated by Django 5.1.15 on 2026-06-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0007_lessonbookmark"),
    ]

    operations = [
        migrations.CreateModel(
            name="XPMultiplierEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("multiplier", models.FloatField(default=1.5)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-start_time"],
            },
        ),
        migrations.AddField(
            model_name="lessonprogress",
            name="base_score",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="lessonprogress",
            name="multiplier_applied",
            field=models.FloatField(default=1.0),
        ),
    ]
