# Generated by Django 5.1.15 on 2026-06-24 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0006_codesubmission_peerreview"),
        ("progress", "0008_xpmultiplierevent_lessonprogress_base_score_and_more"),
    ]

    operations = []
