# Generated by Django 5.1.15 on 2026-06-24 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0009_merge_20260624_0816"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="lessonnote",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="lessonnote",
            name="lesson",
        ),
        migrations.RemoveField(
            model_name="lessonnote",
            name="user",
        ),
        migrations.DeleteModel(
            name="LessonBookmark",
        ),
        migrations.DeleteModel(
            name="LessonNote",
        ),
    ]
