# Generated by Django 5.1.15 on 2026-06-26 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0009_merge_20260624_1225"),
        ("progress", "0009_merge_20260624_1318"),
        ("progress", "0009_merge_20260624_1417"),
        ("progress", "0010_alter_lessonnote_unique_together_and_more"),
    ]

    operations = []
