# Generated by Django 5.1.15 on 2026-06-27 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0006_lesson_prerequisites"),
        ("progress", "0011_merge_20260627_1209"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="codesubmission",
            name="assigned_reviewers",
            field=models.ManyToManyField(
                blank=True, related_name="assigned_reviews", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="codesubmission",
            name="exercise",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="content.exercise",
            ),
        ),
        migrations.AddField(
            model_name="peerreview",
            name="best_practices_rating",
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name="peerreview",
            name="code_correctness_rating",
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name="peerreview",
            name="documentation_rating",
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name="peerreview",
            name="is_approved",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="peerreview",
            name="readability_rating",
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name="codesubmission",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_review", "Pending Review"),
                    ("reviewed", "Reviewed"),
                    ("escalated", "Escalated"),
                    ("changes_requested", "Changes Requested"),
                ],
                db_index=True,
                default="pending_review",
                max_length=25,
            ),
        ),
    ]
