# Generated by Django 5.1.15 on 2026-06-28 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0011_merge_20260625_2105'),
        ('progress', '0012_plagiarismreport_streakprofile'),
        ('progress', '0012_userstreak'),
        ('progress', '0013_achievement_userachievement'),
    ]

    operations = [
    ]
