# Generated by Django 5.1.15 on 2026-06-30 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0014_merge_20260628_0919"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="codesubmission",
            name="assigned_reviewers",
        ),
        migrations.RemoveField(
            model_name="codesubmission",
            name="exercise",
        ),
        migrations.RemoveField(
            model_name="peerreview",
            name="best_practices_rating",
        ),
        migrations.RemoveField(
            model_name="peerreview",
            name="code_correctness_rating",
        ),
        migrations.RemoveField(
            model_name="peerreview",
            name="documentation_rating",
        ),
        migrations.RemoveField(
            model_name="peerreview",
            name="is_approved",
        ),
        migrations.RemoveField(
            model_name="peerreview",
            name="readability_rating",
        ),
        migrations.AlterField(
            model_name="codesubmission",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("reviewed", "Reviewed")],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="Achievement",
        ),
        migrations.DeleteModel(
            name="PlagiarismReport",
        ),
        migrations.DeleteModel(
            name="StreakProfile",
        ),
        migrations.DeleteModel(
            name="UserAchievement",
        ),
        migrations.DeleteModel(
            name="UserStreak",
        ),
    ]
