# Generated by Django 5.1.15 on 2026-06-30 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0007_lessonthread_lessoncomment_and_more"),
        ("progress", "0015_remove_userachievement_achievement_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="codesubmission",
            name="assigned_reviewers",
            field=models.ManyToManyField(
                blank=True, related_name="assigned_reviews", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="codesubmission",
            name="exercise",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="content.exercise",
            ),
        ),
        migrations.AddField(
            model_name="peerreview",
            name="is_approved",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="codesubmission",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_review", "Pending Review"),
                    ("reviewed", "Reviewed"),
                    ("escalated", "Escalated"),
                ],
                db_index=True,
                default="pending_review",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="exerciseattempt",
            name="submitted_command",
            field=models.CharField(default="", max_length=255),
        ),
    ]
