# Generated by Django 4.2.30 on 2026-06-30 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0009_merge_20260624_1417"),
        ("progress", "0016_restore_peer_review_fields"),
    ]

    operations = []
