# Generated by Django 5.1.15 on 2026-06-30 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0017_merge_20260630_1426"),
    ]

    operations = []
