# Generated by Django 5.1.15 on 2026-07-01 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0018_plagiarismreport_streakprofile_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(
                    name="userbadge",
                    unique_together=set(),
                ),
            ],
            database_operations=[],
        ),
    ]
