# Generated by Django 5.1.15 on 2026-07-03 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0018_plagiarismreport_alter_userbadge_unique_together_and_more"),
        ("progress", "0019_streakprofile"),
    ]

    operations = []
