# Generated by ChatGPT on 2026-07-06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("progress", "0021_lessonbookmark"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "activity_type",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "date"], name="idx_daily_activity_user_date"
                    ),
                    models.Index(fields=["-date"], name="idx_daily_activity_date_desc"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="dailyactivity",
            constraint=models.UniqueConstraint(
                fields=["user", "date"], name="unique_user_daily_activity"
            ),
        ),
    ]
