# Generated by Django 4.2.30 on 2026-07-06 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("progress", "0023_lessonprogresssync"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlagiarismReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("similarity_score", models.FloatField()),
                ("is_flagged", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-similarity_score"],
            },
        ),
        migrations.CreateModel(
            name="XPEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("lesson", "Lesson"),
                            ("exercise", "Exercise"),
                            ("pr", "Pull Request"),
                            ("issue", "Issue"),
                            ("review", "Review"),
                            ("badge", "Badge"),
                        ],
                        max_length=20,
                    ),
                ),
                ("source_id", models.PositiveIntegerField(blank=True, null=True)),
                ("base_points", models.PositiveIntegerField()),
                ("multiplier", models.FloatField(default=1.0)),
                ("xp_delta", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="userbadge",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="userbadge",
            constraint=models.UniqueConstraint(
                fields=("user", "badge"), name="unique_user_badge_award"
            ),
        ),
        migrations.AddField(
            model_name="xpevent",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="xp_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="plagiarismreport",
            name="matched_submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matched_in_reports",
                to="progress.codesubmission",
            ),
        ),
        migrations.AddField(
            model_name="plagiarismreport",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plagiarism_reports",
                to="progress.codesubmission",
            ),
        ),
        migrations.AddIndex(
            model_name="xpevent",
            index=models.Index(
                fields=["user", "source_type"], name="idx_xp_user_source"
            ),
        ),
        migrations.AddIndex(
            model_name="xpevent",
            index=models.Index(fields=["-created_at"], name="idx_xp_created_desc"),
        ),
        migrations.AlterUniqueTogether(
            name="plagiarismreport",
            unique_together={("submission", "matched_submission")},
        ),
    ]
