# Generated by Django 5.0.14 on 2026-07-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0024_plagiarismreport_xpevent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="peerreview",
            name="is_hidden",
            field=models.BooleanField(default=False),
        ),
    ]
