# Generated by Django 5.0.14 on 2026-07-09 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0018_plagiarismreport_streakprofile_and_more"),
        ("progress", "0025_peerreview_is_hidden"),
    ]

    operations = []
