# Generated by Django 5.0.14 on 2026-07-10 04:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0026_merge_20260709_0732"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lessonprogresssync",
            name="score",
            field=models.PositiveIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000),
                ],
            ),
        ),
    ]
