# Generated by Django 5.0.14 on 2026-07-09 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0026_merge_20260709_0732"),
    ]

    operations = []
