# Generated by Django 5.0.14 on 2026-07-09 12:22

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0027_merge_20260709_1752"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="lessonprogresssync",
            name="score",
            field=models.PositiveIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000),
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="xpevent",
            constraint=models.CheckConstraint(
                check=models.Q(("base_points__gte", 0), ("base_points__lte", 1000)),
                name="base_points_range_constraint",
            ),
        ),
    ]
