# Generated by Django 5.0.14 on 2026-07-11 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_lesson_js_exercise_profile'),
        ('progress', '0028_alter_lessonprogresssync_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_notes', to='content.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlagiarismReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField()),
                ('is_flagged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matched_in_reports', to='progress.codesubmission')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plagiarism_reports', to='progress.codesubmission')),
            ],
            options={
                'ordering': ['-similarity_score'],
                'unique_together': {('submission', 'matched_submission')},
            },
        ),
    ]
