# Generated by Django 5.0.14 on 2026-07-13 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0022_alter_userbadge_unique_together'),
        ('progress', '0029_usernote_plagiarismreport'),
    ]

    operations = [
    ]
