# Generated by Django 5.0.14 on 2026-07-13 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0030_merge_20260713_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='streakprofile',
            name='streak_freezes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='xpevent',
            name='source_type',
            field=models.CharField(choices=[('lesson', 'Lesson'), ('exercise', 'Exercise'), ('pr', 'Pull Request'), ('issue', 'Issue'), ('review', 'Review'), ('badge', 'Badge'), ('shop', 'Shop Purchase')], max_length=20),
        ),
    ]
