# Generated by Django 5.0.14 on 2026-07-15 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0031_streakprofile_streak_freezes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('xp_boost_multiplier', models.FloatField(default=1.0)),
                ('boost_activity_type', models.CharField(blank=True, choices=[('lesson', 'Lesson'), ('exercise', 'Exercise'), ('pr', 'Pull Request'), ('issue', 'Issue'), ('review', 'Review')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.AlterField(
            model_name='xpevent',
            name='source_type',
            field=models.CharField(choices=[('lesson', 'Lesson'), ('exercise', 'Exercise'), ('pr', 'Pull Request'), ('issue', 'Issue'), ('review', 'Review'), ('badge', 'Badge'), ('shop', 'Shop Purchase'), ('milestone', 'Milestone Track')], max_length=20),
        ),
        migrations.CreateModel(
            name='TrackMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('activity_type', models.CharField(choices=[('lesson', 'Lesson completions'), ('exercise', 'Exercise completions'), ('xp', 'Total XP earned')], default='xp', max_length=50)),
                ('target_value', models.PositiveIntegerField(default=100)),
                ('xp_boost', models.PositiveIntegerField(default=0, help_text='One-time XP bonus awarded on completing this milestone.')),
                ('badge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milestones', to='progress.badge')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='progress.season')),
            ],
            options={
                'ordering': ['target_value'],
            },
        ),
        migrations.CreateModel(
            name='UserMilestoneCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='progress.trackmilestone')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestone_completions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StreakRecoveryPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_date', models.DateField()),
                ('previous_streak', models.PositiveIntegerField(default=0)),
                ('quiz_target', models.PositiveIntegerField(default=1)),
                ('quiz_progress', models.PositiveIntegerField(default=0)),
                ('reading_target', models.PositiveIntegerField(default=15)),
                ('reading_progress', models.PositiveIntegerField(default=0)),
                ('code_target', models.PositiveIntegerField(default=1)),
                ('code_progress', models.PositiveIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak_recovery_plan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'target_date'], name='idx_recovery_user_date')],
            },
        ),
        migrations.AddConstraint(
            model_name='usermilestonecompletion',
            constraint=models.UniqueConstraint(fields=('user', 'milestone'), name='unique_user_milestone_completion'),
        ),
    ]
