# Generated by Django 5.1.15 on 2026-06-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="embedding",
            field=models.JSONField(
                blank=True,
                help_text="Pre-computed semantic embedding vector",
                null=True,
            ),
        ),
    ]
