# Generated by Django 5.1.15 on 2026-06-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "logo_url",
                    models.URLField(
                        blank=True, help_text="URL to the organization's logo"
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "popularity_score",
                    models.IntegerField(
                        default=0, help_text="Higher score means more popular"
                    ),
                ),
            ],
            options={
                "ordering": ["-popularity_score"],
            },
        ),
    ]
