# Generated by Django 4.2.30 on 2026-06-22 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_lesson_organization"),
        ("content", "0003_organization"),
    ]

    operations = []
