# Generated by Django 4.2.30 on 2026-06-22 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_merge_0003_lesson_organization_0003_organization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="content.organization",
            ),
        ),
    ]
