# Generated by Django 5.1.15 on 2026-06-27 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_alter_lesson_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="prerequisites",
            field=models.ManyToManyField(
                blank=True, related_name="dependents", to="content.lesson"
            ),
        ),
    ]
