# Generated by Django 5.0.14 on 2026-07-09 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0008_lessonfeedback"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="js_exercise",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="A short biography or description.",
                        max_length=160,
                    ),
                ),
                (
                    "github_link",
                    models.URLField(
                        blank=True, default="", help_text="GitHub profile URL"
                    ),
                ),
                (
                    "linkedin_link",
                    models.URLField(
                        blank=True, default="", help_text="LinkedIn profile URL"
                    ),
                ),
                (
                    "portfolio_link",
                    models.URLField(
                        blank=True, default="", help_text="Personal portfolio URL"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
