# Generated by Django 5.0.14 on 2026-07-12 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_lesson_js_exercise_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='content.lesson')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
