# Generated by Django 5.0.14 on 2026-07-12 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='domainevent',
            new_name='events_doma_event_t_4e98ae_idx',
            old_name='events_doma_event_t_5c09ac_idx',
        ),
        migrations.RenameIndex(
            model_name='domainevent',
            new_name='events_doma_event_n_85b104_idx',
            old_name='events_doma_event_n_af6668_idx',
        ),
        migrations.RenameIndex(
            model_name='domainevent',
            new_name='events_doma_occurre_8aec82_idx',
            old_name='events_doma_occurre_7f74e3_idx',
        ),
        migrations.RenameIndex(
            model_name='domainevent',
            new_name='events_doma_actor_i_3cb6c3_idx',
            old_name='events_doma_actor_i_ee902a_idx',
        ),
    ]
