name: Blank Issue
description: Create a blank issue with minimal structure
title: "[ISSUE]: "
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Detailed description of the issue.
    validations:
      required: true
  - type: checkboxes
    id: program
    attributes:
      label: Contributor Program
      options:
        - label: I am contributing under SSoC 2026 / ECSoC 2026
