# Generated by Django 5.0.14 on 2026-07-12 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feature_flags', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeatureFlag',
        ),
    ]
