# Generated by Django 5.0.14 on 2026-07-15 14:00

import apps.webhooks.models
from django.db import migrations, models


def encrypt_existing_secrets(apps, schema_editor):
    WebhookEndpoint = apps.get_model("webhooks", "WebhookEndpoint")
    from apps.webhooks.security import encrypt_secret

    for endpoint in WebhookEndpoint.objects.all():
        if endpoint.secret_plain and not endpoint.encrypted_secret:
            endpoint.encrypted_secret = encrypt_secret(endpoint.secret_plain)
            endpoint.save(update_fields=["encrypted_secret"])


class Migration(migrations.Migration):

    dependencies = [
        ("webhooks", "0002_webhookdelivery_retry_dlq"),
    ]

    operations = [
        migrations.RenameField(
            model_name="webhookendpoint",
            old_name="secret",
            new_name="secret_plain",
        ),
        migrations.AlterField(
            model_name="webhookendpoint",
            name="secret_plain",
            field=models.CharField(
                blank=True,
                db_column="secret",
                default=apps.webhooks.models.generate_secret,
                help_text="Legacy plaintext secret column, to be removed after data migration.",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="webhookendpoint",
            name="encrypted_old_secret",
            field=models.TextField(
                blank=True,
                help_text="Encrypted previous shared secret (for rotation grace period).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="webhookendpoint",
            name="encrypted_secret",
            field=models.TextField(
                blank=True,
                help_text="Encrypted shared secret used to sign the webhook payloads.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="webhookendpoint",
            name="old_secret_expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Expiration timestamp for the old secret.",
                null=True,
            ),
        ),
        migrations.RunPython(
            encrypt_existing_secrets,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
