# Generated by Django 5.0.14 on 2026-07-15 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0003_add_encrypted_secrets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webhookendpoint',
            name='secret_plain',
        ),
    ]
