# Generated by Django 5.1.15 on 2026-06-23 15:56

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_userprofile_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="last_password_change",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2026, 6, 23, 15, 56, 7, 712929, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
