# Generated by Django 5.1.15 on 2026-06-24 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_magiclinktoken"),
        ("accounts", "0004_userprofile_last_password_change"),
        ("accounts", "0004_userprofile_timezone"),
    ]

    operations = []
