# Generated by Django 5.1.15 on 2026-06-24 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_merge_20260624_1029"),
        ("accounts", "0006_userprofile_cover_image"),
    ]

    operations = []
