# Generated by Django 5.1.15 on 2026-06-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_merge_20260624_0816"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="github_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="linkedin_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="twitter_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
    ]
