# Generated by Django 5.1.15 on 2026-06-27 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_userprofile_timezone"),
        ("accounts", "0007_merge_20260624_1225"),
        ("accounts", "0007_merge_20260624_1318"),
        ("accounts", "0007_merge_20260624_1417"),
        ("accounts", "0008_userprofile_github_url_userprofile_linkedin_url_and_more"),
    ]

    operations = []
