# Generated by Django 5.1.15 on 2026-06-25 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_userprofile_timezone"),
        ("accounts", "0008_userprofile_github_url_userprofile_linkedin_url_and_more"),
    ]

    operations = []
