# Generated by Django 5.1.15 on 2026-06-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_merge_20260625_2105"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="dnd_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Temporarily disable non-critical email notifications.",
            ),
        ),
    ]
