# Generated by Django 4.2.11 on 2026-06-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_userprofile_dnd_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="theme_preference",
            field=models.CharField(
                choices=[
                    ("light", "Light"),
                    ("dark", "Dark"),
                    ("system", "System Default"),
                ],
                default="system",
                help_text="User's preferred UI theme.",
                max_length=20,
            ),
        ),
    ]
