# Generated by Django 5.1.15 on 2026-06-30 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_merge_20260628_0919"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="dnd_enabled",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="theme_preference",
        ),
    ]
