# Generated by Django 5.0.14 on 2026-07-10 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_alter_userprofile_timezone"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="receive_weekly_digest",
            field=models.BooleanField(
                default=True,
                help_text="Receive automated weekly progress digest emails",
            ),
        ),
    ]
