# Generated by Django 5.0.14 on 2026-07-10 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_alter_userprofile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                blank=True, max_length=255, null=True, upload_to="avatars/"
            ),
        ),
    ]
