# Generated by Django 5.0.14 on 2026-07-10 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_userprofile_receive_weekly_digest'),
        ('accounts', '0016_alter_userprofile_avatar'),
    ]

    operations = [
    ]
