# Generated by Django 5.0.14 on 2026-07-14 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_case_insensitive_username_unique'),
        ('accounts', '0020_alter_userprofile_jwt_token_version_and_more'),
    ]

    operations = [
    ]
