# Generated by Django 5.0.14 on 2026-07-15 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_merge_20260714_1801'),
        ('accounts', '0021_merge_20260714_2346'),
    ]

    operations = [
    ]
