# Generated by Django 5.0.14 on 2026-07-16 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0022_merge_20260715_1925"),
        ("accounts", "0022_merge_20260715_1959"),
        ("accounts", "0022_merge_20260715_2013"),
    ]

    operations = []
