# Generated by Django 5.0.14 on 2026-07-16 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0023_merge_20260715_2159"),
        ("accounts", "0023_merge_20260716_1300"),
        ("accounts", "0023_merge_20260716_1330"),
    ]

    operations = []
