# Generated by Django 5.0.14 on 2026-07-18 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0023_merge_20260716_1436"),
        ("accounts", "0024_merge_20260716_1841"),
        ("accounts", "0024_merge_20260716_1849"),
    ]

    operations = []
